# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HIGH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HIGH

  target 'HIGHTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
